jwt:  #jwt 관련 정보
  key: ${JWT_SECRET_KEY}

#mail: #관리자 권한 메일
#  address:
#    admin: qudtn7383@gmail.com, zzz@gmail.com, guest@test.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile
          naver:
            client-id: ${N_CLIENT_ID}
            client-secret: ${N_CLIENT_ID}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: ${K_CLIENT_ID}
            client-secret: ${K_CLIENT_ID}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
           naver:
             authorization_uri: https://nid.naver.com/oauth2.0/authorize
             token_uri: https://nid.naver.com/oauth2.0/token
             user-info-uri: https://openapi.naver.com/v1/nid/me
             user_name_attribute: response

           kakao:
             authorization-uri: https://kauth.kakao.com/oauth/authorize
             token-uri: https://kauth.kakao.com/oauth/token
             user-info-uri: https://kapi.kakao.com/v2/user/me
             user-name-attribute: id