jwt:  #jwt 관련 정보
  key: ${JWT_SECRET_KEY}

#mail: #관리자 권한 메일
#  address:
#    admin: qudtn7383@gmail.com, zzz@gmail.com, guest@test.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile