jwt:  #jwt 관련 정보
  key: ${JWT_SECRET_KEY}

#mail: #관리자 권한 메일
#  address:
#    admin: qudtn7383@gmail.com, zzz@gmail.com, guest@test.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 870024467696-q525mqupm61no6npbb791bme29sd0rhv.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: ATs53kDsTYH9E5pM_KHU
            client-secret: VVHuPXgYdn
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 44bd4f3167fdc8032d045dcd5f3a76c
            client-secret: 7rv4qX1oi1eqyYBn8uClRM2FSPCJIwmT
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
           naver:
             authorization_uri: https://nid.naver.com/oauth2.0/authorize
             token_uri: https://nid.naver.com/oauth2.0/token
             user-info-uri: https://openapi.naver.com/v1/nid/me
             user_name_attribute: response

           kakao:
             authorization-uri: https://kauth.kakao.com/oauth/authorize
             token-uri: https://kauth.kakao.com/oauth/token
             user-info-uri: https://kapi.kakao.com/v2/user/me
             user-name-attribute: id