jwt:  #jwt 관련 정보
  key: ${JWT_SECRET_KEY}

#mail: #관리자 권한 메일
#  address:
#    admin: qudtn7383@gmail.com, zzz@gmail.com, guest@test.com
#payment:
#  cid: TC0ONETIME   #가맹점 임시 코드
#  admin_key: ${ADMIN_KEY} #카카오 어플리케이션 어드민 키
#  host: https://kapi.kakao.com/v1/payment
#  url: localhost:8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile